import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/index.ecad4d73.css'
import '../styles/index.18257fd8.css'
import '../styles/index.page.274d5a15.css'
import '../styles/hooks.331a9899.css'
import '../styles/index.74861cf6.css'
import '../styles/AwardBall.9c1b7ab7.css'
import '../styles/app.45cfe5da.css'
import '../styles/_default.page.client.694535e5.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='darken'>{children}</body>
    </html>
  )
}
