import React from 'react'
import '../../../styles/GroupPageLayout.6f234913.css'
import { HelpSideBar } from '@/components'

function page() {
    return (
        <HelpSideBar>
            <div className="right-info">
                <div style={{ opacity: 1, transform: 'none' }}>
                    <div className="doc-page snxvmcx">
                        <div className="item">
                            <section>
                                <h2>Fiat Currency Display for Cryptocurrency Players</h2>
                                <p>
                                    Players who elect to view their cryptocurrency balances in terms of fiat currency equivalents
                                    (&quot;Converted Balances&quot;)
                                    should expressly recognize that such Converted Balances are for reference purposes only and
                                    serve as approximate
                                    estimates. Although BC Game endorses diligent efforts to ensure that the conversion rates
                                    utilized are accurate and
                                    updated, all transactions, wagers, and settlements conducted on our platform are denominated and
                                    settled in
                                    cryptocurrency.
                                </p>
                                <h2>Limitation of Liability</h2>
                                <p>
                                    BC.GAME expressly disclaims any liability for inaccuracies, errors, or discrepancies in the
                                    Converted Balances
                                    presented. Players are hereby advised that the cryptocurrency amount shall be deemed the primary
                                    value for all
                                    transactions and wagers, and any reliance on estimated fiat conversions, known as Converted
                                    Balances, is at the sole
                                    risk of the player.
                                </p>
                                <h2>Third-Party Games</h2>
                                <p>
                                    Our platform may integrate third-party games offering the display of fiat conversion options
                                    (&quot;Third-Party Converted
                                    Balances&quot;). BC.GAME shall not be held accountable for any discrepancies between the Converted
                                    Balances shown on the
                                    website and the Third-Party Converted Balances presented within these third-party games.
                                </p>
                                <h2>Reporting Discrepancies</h2>
                                <p>
                                    We actively encourage players to promptly report any discrepancies or irregularities observed
                                    between the Converted
                                    Balances displayed and the actual cryptocurrency amounts. Such reporting should be directed to
                                    our support team for
                                    immediate review and action. Timely reporting assists us in the continuous improvement of player
                                    experience and the
                                    accuracy of information presented.
                                </p>
                                <h2>Coin accuracy limit</h2>
                                <p>
                                    Due to the limitation of data storage accuracy, changes in the amount less
                                    than a certain amount will not take effect. The minimum accuracy of most
                                    coins is consistent with the currency accuracy of the blockchain. For
                                    example, the minimum unit of SATS is 1. The minimum data storage accuracy of
                                    each coin is shown in the following table:
                                </p>
                            </section>

                        </div>
                        <div className="item">
                            <table className="ui-table is-stripe">
                                <thead>
                                    <tr>
                                        <th><span>Currency</span></th>
                                        <th><span>Coin Accuracy Limit</span></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><span>BCD</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>USDT</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ETH</span></td>
                                        <td><span>0.0000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BTC</span></td>
                                        <td><span>0.0000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TRX</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BNB</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>LTC</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XRP</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>LINK</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BUSD</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>DOT</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>USDC</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>DOGE</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SOL</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BCH</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XLM</span></td>
                                        <td><span>0.001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ATOM</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SATS</span></td>
                                        <td><span>1</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>EOS</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MATIC</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>DAI</span></td>
                                        <td><span>0.00001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>APT</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BCL</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AAVE</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>YFI</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XEN</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>WLD</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>HNT</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>RUNE</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SUI</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BTCB</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ARB</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GMX</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BTG</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ALGO</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BIGTIME</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ARS</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ICP</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BLUR</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>USDC.e</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>HBAR</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>PEPE</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NANO</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>JOE</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KAVA</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>USDT.e</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>THETA</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>CLP</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NEXO</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TFUEL</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>LUNA</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>UNI</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>OP</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TAMA</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>FIL</span></td>
                                        <td><span>0.000000000000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AMPL</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>IDR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>DGB</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GMT</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>JPEG</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ICX</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>WBNB</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MAGIC</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XTZ</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GST</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SAMO</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ROSE</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>WAXP</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SNACK</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KLAY</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>COP</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>UAH</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KES</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XOF</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XAF</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>UZS</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KRW</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KGS</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>EUR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MXN</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MMK</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GBP</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TZS</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>VND</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>RUB</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>EGP</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AZN</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>JPY</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MYR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GHS</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AUD</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BDT</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>UGX</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>THB</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KZT</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>PEN</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NZD</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KAS</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KHR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NGN</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MDL</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NOK</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>CAD</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>PHP</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>LUNC</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>WETH</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>PKR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TON</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AED</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BANANO</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>XMR</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BSV</span></td>
                                        <td><span>0.0000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>KSM</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SUSHI</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>WBTC</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SNX</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>CRO</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>MANA</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>DASH</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BAT</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ENJ</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>CRV</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>JST</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SUNOLD</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>CAKE</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TWT</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GODS</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>VTHO</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NFT</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BIT</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>YGG</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>IOTX</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SHIB</span></td>
                                        <td><span>1</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NEAR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AVAX</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>FTM</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ONE</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ETC</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>USTC</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>CELO</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TOMO</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ADA</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>VET</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>RVN</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>WAVES</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SUNNEW</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>SAND</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AMP</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>BRL</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>DCR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>TUSD</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>EGLD</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>NEWBTT</span></td>
                                        <td><span>1</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>QTUM</span></td>
                                        <td><span>0.0001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>INR</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>GALA</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>APE</span></td>
                                        <td><span>0.000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>HEX</span></td>
                                        <td><span>0.00000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>AXS</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>ZIL</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>PEOPLE</span></td>
                                        <td><span>0.000000001</span></td>
                                    </tr>
                                    <tr>
                                        <td><span>JB</span></td>
                                        <td><span>1</span></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </HelpSideBar>
    )
}

export default page